-- TODO: check what has been copy-pasted from 1.1
-- TODO: check attributes in 2.0

data:extend(
    {
        {
            type = "logistic-container",
            name = "logistic-chest-passive-provider-4d",
            icon = "__base__/graphics/icons/logistic-chest-passive-provider.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-chest-passive-provider-4d" },
            max_health = 150,
            corpse = "small-remnants",
            collision_box = { { -0.35, -0.35 }, { 0.35, 0.35 } },
            selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
            fast_replaceable_group = "container",
            inventory_size = 50000,
            logistic_mode = "passive-provider",
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            impact_category = "metal",
            picture =
            {
                filename = "__base__/graphics/entity/logistic-chest/hr-logistic-chest-passive-provider.png",
                priority = "extra-high",
                width = 66,
                height = 74,
                frame_count = 7,
                shift = util.by_pixel(0, -2),
                scale = 0.5
            },

        },
        {
            type = "logistic-container",
            name = "logistic-chest-active-provider-4d",
            icon = "__base__/graphics/icons/logistic-chest-active-provider.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-chest-active-provider-4d" },
            max_health = 150,
            corpse = "small-remnants",
            collision_box = { { -0.35, -0.35 }, { 0.35, 0.35 } },
            selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
            fast_replaceable_group = "container",
            inventory_size = 50000,
            logistic_mode = "active-provider",
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            impact_category = "metal",
            picture =
            {
                filename = "__base__/graphics/entity/logistic-chest/hr-logistic-chest-active-provider.png",
                priority = "extra-high",
                width = 66,
                height = 74,
                frame_count = 7,
                shift = util.by_pixel(0, -2),
                scale = 0.5
            },

        },
        {
            type = "logistic-container",
            name = "logistic-chest-storage-4d",
            icon = "__base__/graphics/icons/logistic-chest-storage.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-chest-storage-4d" },
            max_health = 150,
            corpse = "small-remnants",
            collision_box = { { -0.35, -0.35 }, { 0.35, 0.35 } },
            selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
            fast_replaceable_group = "container",
            inventory_size = 50000,
            logistic_mode = "storage",
            max_logistic_slots = 1,
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            impact_category = "metal",
            picture =
            {
                filename = "__base__/graphics/entity/logistic-chest/hr-logistic-chest-storage.png",
                priority = "extra-high",
                width = 66,
                height = 74,
                frame_count = 7,
                shift = util.by_pixel(0, -2),
                scale = 0.5
            },

        },
        {
            type = "logistic-container",
            name = "logistic-chest-requester-4d",
            icon = "__base__/graphics/icons/logistic-chest-requester.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-chest-requester-4d" },
            max_health = 150,
            corpse = "small-remnants",
            collision_box = { { -0.35, -0.35 }, { 0.35, 0.35 } },
            selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
            fast_replaceable_group = "container",
            inventory_size = 50000,
            logistic_mode = "requester",
            logistic_slots_count = 32,
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            picture =
            {
                filename = "__base__/graphics/entity/logistic-chest/hr-logistic-chest-requester.png",
                priority = "extra-high",
                width = 66,
                height = 74,
                frame_count = 7,
                shift = util.by_pixel(0, -2),
                scale = 0.5
            },
        },
        {
            type = "logistic-container",
            name = "logistic-chest-buffer-4d",
            icon = "__base__/graphics/icons/logistic-chest-buffer.png",
            icon_size = 32,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-chest-buffer-4d" },
            max_health = 150,
            corpse = "small-remnants",
            collision_box = { { -0.35, -0.35 }, { 0.35, 0.35 } },
            selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
            fast_replaceable_group = "container",
            inventory_size = 50000,
            logistic_mode = "buffer",
            logistic_slots_count = 32,
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            picture =
            {
                filename = "__base__/graphics/entity/logistic-chest/hr-logistic-chest-buffer.png",
                priority = "extra-high",
                width = 66,
                height = 72,
                frame_count = 7,
                shift = util.by_pixel(0, -2),
                scale = 0.5
            },
        },
        {
            type = "logistic-container",
            name = "logistic-house-passive-provider",
            icon = "__base__/graphics/icons/logistic-chest-passive-provider.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-house-passive-provider" },
            max_health = 750,
            corpse = "small-remnants",
            collision_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            selection_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            fast_replaceable_group = "container",
            inventory_size = 2000,
            logistic_mode = "passive-provider",
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            impact_category = "metal",
            picture =
            {
                filename = "__Darkstar2.0__/graphics/entity/storage/warehouse-passive-provider.png",
                priority = "extra-high",
                width = 550,
                height = 550,
                shift = { 0.1, 0 }
            },

        },
        {
            type = "logistic-container",
            name = "logistic-house-buffer",
            icon = "__base__/graphics/icons/logistic-chest-passive-provider.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-house-buffer" },
            max_health = 750,
            corpse = "small-remnants",
            collision_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            selection_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            fast_replaceable_group = "container",
            inventory_size = 2000,
            logistic_mode = "buffer",
            logistic_slots_count = 32,
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            impact_category = "metal",
            picture =
            {
                filename = "__Darkstar2.0__/graphics/entity/storage/warehouse-buffer.png",
                priority = "extra-high",
                width = 550,
                height = 550,
                shift = { 0.1, 0 }
            },

        },
        {
            type = "logistic-container",
            name = "logistic-house-active-provider",
            icon = "__base__/graphics/icons/logistic-chest-active-provider.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-house-active-provider" },
            max_health = 750,
            corpse = "small-remnants",
            collision_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            selection_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            fast_replaceable_group = "container",
            inventory_size = 2000,
            logistic_mode = "active-provider",
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            impact_category = "metal",
            picture =
            {
                filename = "__Darkstar2.0__/graphics/entity/storage/warehouse-active-provider.png",
                priority = "extra-high",
                width = 550,
                height = 550,
                shift = { 0.1, 0 }
            },

        },
        {
            type = "logistic-container",
            name = "logistic-house-storage",
            icon = "__base__/graphics/icons/logistic-chest-storage.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-house-storage" },
            max_health = 750,
            corpse = "small-remnants",
            collision_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            selection_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            fast_replaceable_group = "container",
            inventory_size = 2000,
            logistic_mode = "storage",
            max_logistic_slots = 1,
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            impact_category = "metal",
            picture =
            {
                filename = "__Darkstar2.0__/graphics/entity/storage/warehouse-storage.png",
                priority = "extra-high",
                width = 550,
                height = 550,
                shift = { 0.1, 0 }
            },

        },
        {
            type = "logistic-container",
            name = "logistic-house-requester",
            icon = "__base__/graphics/icons/logistic-chest-requester.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "logistic-house-requester" },
            max_health = 750,
            corpse = "small-remnants",
            collision_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            selection_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            fast_replaceable_group = "container",
            inventory_size = 2000,
            logistic_mode = "requester",
            logistic_slots_count = 32,
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            picture =
            {
                filename = "__Darkstar2.0__/graphics/entity/storage/warehouse-requester.png",
                priority = "extra-high",
                width = 550,
                height = 550,
                shift = { 0.1, 0 }
            },

        },
        {
            type = "container",
            name = "storage-house",
            icon = "__base__/graphics/icons/logistic-chest-requester.png",
            icon_size = 64,
            flags = { "placeable-player", "player-creation" },
            minable = { mining_time = 0.5, result = "storage-house" },
            max_health = 750,
            corpse = "small-remnants",
            collision_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            selection_box = { { -8.5, -5.0 }, { 3.0, 7.0 } },
            fast_replaceable_group = "container",
            inventory_size = 2000,
            open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
            close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
            picture =
            {
                filename = "__Darkstar2.0__/graphics/entity/storage/warehouse.png",
                priority = "extra-high",
                width = 550,
                height = 550,
                shift = { 0.1, 0 }
            },

        },

    }
)
