require("item.advanced-materials")
require("item.ammo")
-- require("item.base-packs")  -- TODO: item.cards
-- require("item.belts")
-- require("item.capsule")
require("item.cards")
-- require("item.computer")
-- require("item.Darkstar-6")
-- require("item.Darkstar-7")
-- require("item.Darkstar-9")
-- require("item.Darkstar-010")
-- require("item.Darkstar-011")
require("item.data")
-- require("item.drills")
-- require("item.equipment")
-- require("item.filters")
require("item.generators")
-- require("item.gun")
-- require("item.inserter")
-- require("item.intermediate-product")
-- require("item.launch-items")
-- require("item.Lights")
-- require("item.locomotive")
-- require("item.misc")
-- require("item.planck")
-- require("item.probes")
-- require("item.radar")
require("item.random")
-- require("item.research-packs")
-- require("item.resources")
-- require("item.science-pack")
-- require("item.servers")
-- require("item.solar-panel")
-- require("item.Technical")
-- require("item.turrets")
-- require("item.vehicle")
