-- TODO: apply these to recipe allow_productivity 
function productivitymodulelimitations()
return
      {
        "sulfuric-acid",
        "basic-oil-processing",
        "advanced-oil-processing",
        "coal-liquefaction",
        "heavy-oil-cracking",
        "light-oil-cracking",
        "solid-fuel-from-light-oil",
        "solid-fuel-from-heavy-oil",
        "solid-fuel-from-petroleum-gas",
        "lubricant",
        "iron-plate",
        "copper-plate",
        "steel-plate",
        "stone-brick",
        "sulfur",
        "plastic-bar",
        "empty-barrel",
        "uranium-processing",
        "copper-cable",
        "iron-stick",
        "iron-gear-wheel",
        "electronic-circuit",
        "advanced-circuit",
        "processing-unit",
        "engine-unit",
        "electric-engine-unit",
        "uranium-fuel-cell",
        "explosives",
        "battery",
        "flying-robot-frame",
        "low-density-structure",
        "rocket-fuel",
        "rocket-control-unit",
        "rocket-part",
        "automation-science-pack",
        "logistic-science-pack",
        "chemical-science-pack",
        "military-science-pack",
        "production-science-pack",
        "utility-science-pack",
        "link",
        "fuse-box",
        "ram",
        "gpu",
        "cpu",
        "fan",
        "diode",
        "mother-board",
        "seed-crystal",
        "silicon",
        "quantum-fuel",
        "sand",
        "sand2",
        "computer",
        "lead-plate",
        "gold-plate",
        "glass",
        "leaded-glass",
        "micro-processor",
        "star-copper",
        "star-iron",
        "star-lead",
        "star-gold",
        "star-uranium",
        "star-stone",
        "dark-matter",
        "antithetical-matter",
        "bio-research",
        "advanced-photovoltaic-cells",
        "solar-waffer",
        "module-componant",
        "empty-regulator",
        "platinum-plate",
        "selenium-plate",
        "tellurium-plate",
        "silver-plate",
        "antimony-plate",
        "lithium-plate",
        "ciusitral-plate",
        "lithusarium-plate",
        "rhusanthium-plate",
        "lithium-steel-plate",
        "lithium-steel-plate2",
        "filter-tray-2",
        "filter-tray",
        "flywheel",
        "quantum-blood",
      }
end

data:extend(
    {
        {
            type = "module",
            name = "filter-module",
            icon = "__Darkstar2.0__/graphics/items/filter-module.png",
            icon_size = 32,

            subgroup = "module",
            category = "filter",
            tier = 1,
            order = "a[1]-a[1]",
            stack_size = 50,
            effect = { speed = -0.5 }
        },
        {
            type = "module",
            name = "speed-module-4",
            icon = "__Darkstar2.0__/graphics/items/speed-module-4.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-c[speed-module-4]",
            stack_size = 50,
            effect = { speed = 0.6, consumption = 0.6 }
        },
        {
            type = "module",
            name = "speed-module-5",
            icon = "__Darkstar2.0__/graphics/items/speed-module-5.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-d[speed-module-5]",
            stack_size = 50,
            effect = { speed = 0.7, consumption = 0.7 }
        },
        {
            type = "module",
            name = "speed-module-6",
            icon = "__Darkstar2.0__/graphics/items/speed-module-6.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-e[speed-module-6]",
            stack_size = 50,
            effect = { speed = 0.9, consumption = 0.9 }
        },
        {
            type = "module",
            name = "speed-module-7",
            icon = "__Darkstar2.0__/graphics/items/speed-module-7.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-f[speed-module-7]",
            stack_size = 50,
            effect = { speed = 1.0, consumption = 1.0 }
        },
        {
            type = "module",
            name = "speed-module-8",
            icon = "__Darkstar2.0__/graphics/items/speed-module-8.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-g[speed-module-8]",
            stack_size = 50,
            effect = { speed = 1.1, consumption = 1.1 }
        },
        {
            type = "module",
            name = "speed-module-9",
            icon = "__Darkstar2.0__/graphics/items/speed-module-9.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-h[speed-module-9]",
            stack_size = 50,
            effect = { speed = 1.3, consumption = 1.3 }
        },
        {
            type = "module",
            name = "speed-module-10",
            icon = "__Darkstar2.0__/graphics/items/speed-module-10.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-i[speed-module-10]",
            stack_size = 50,
            effect = { speed = 1.4, consumption = 1.4 }
        },
        {
            type = "module",
            name = "speed-module-11",
            icon = "__Darkstar2.0__/graphics/items/speed-module-11.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-j[speed-module-11]",
            stack_size = 50,
            effect = { speed = 1.5, consumption = 1.5 }
        },
        {
            type = "module",
            name = "speed-module-12",
            icon = "__Darkstar2.0__/graphics/items/speed-module-12.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-k[speed-module-12]",
            stack_size = 50,
            effect = { speed = 1.7, consumption = 1.7 }
        },
        {
            type = "module",
            name = "speed-module-13",
            icon = "__Darkstar2.0__/graphics/items/speed-module-13.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-l[speed-module-13]",
            stack_size = 50,
            effect = { speed = 1.8, consumption = 1.8 }
        },
        {
            type = "module",
            name = "speed-module-14",
            icon = "__Darkstar2.0__/graphics/items/speed-module-14.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-m[speed-module-14]",
            stack_size = 50,
            effect = { speed = 1.9, consumption = 1.9 }
        },
        {
            type = "module",
            name = "speed-module-15",
            icon = "__Darkstar2.0__/graphics/items/speed-module-15.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-n[speed-module-15]",
            stack_size = 50,
            effect = { speed = 2.0, consumption = 2.0 }
        },
        {
            type = "module",
            name = "speed-module-16",
            icon = "__Darkstar2.0__/graphics/items/speed-module-16.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 2.2, consumption = 2.2 }
        },
        {
            type = "module",
            name = "speed-module-17",
            icon = "__Darkstar2.0__/graphics/items/speed-module-17.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 2.4, consumption = 2.4 }
        },
        {
            type = "module",
            name = "speed-module-18",
            icon = "__Darkstar2.0__/graphics/items/speed-module-18.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 2.6, consumption = 2.6 }
        },
        {
            type = "module",
            name = "speed-module-19",
            icon = "__Darkstar2.0__/graphics/items/speed-module-19.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 2.8, consumption = 2.8 }
        },
        {
            type = "module",
            name = "speed-module-20",
            icon = "__Darkstar2.0__/graphics/items/speed-module-20.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 3.0, consumption = 3.0 }
        },
        {
            type = "module",
            name = "speed-module-21",
            icon = "__Darkstar2.0__/graphics/items/speed-module-21.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 3.2, consumption = 3.2 }
        },
        {
            type = "module",
            name = "speed-module-22",
            icon = "__Darkstar2.0__/graphics/items/speed-module-22.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 3.4, consumption = 3.4 }
        },
        {
            type = "module",
            name = "speed-module-23",
            icon = "__Darkstar2.0__/graphics/items/speed-module-23.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 3.6, consumption = 3.6 }
        },
        {
            type = "module",
            name = "speed-module-24",
            icon = "__Darkstar2.0__/graphics/items/speed-module-24.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 3.8, consumption = 3.8 }
        },
        {
            type = "module",
            name = "speed-module-25",
            icon = "__Darkstar2.0__/graphics/items/speed-module-25.png",
            icon_size = 32,

            subgroup = "module",
            category = "speed",
            tier = 1,
            order = "a[speed]-o[speed-module-16]",
            stack_size = 50,
            effect = { speed = 4.0, consumption = 4.0 }
        },
        {
            type = "module",
            name = "effectivity-module-4",
            icon = "__Darkstar2.0__/graphics/items/effectivity-module-4.png",
            icon_size = 32,

            subgroup = "module",
            category = "effectivity",
            tier = 1,
            order = "c[effectivity]-x[effectivity-module-]",
            stack_size = 50,
            effect = { consumption = -0.8 }
        },
        {
            type = "module",
            name = "effectivity-module-5",
            icon = "__Darkstar2.0__/graphics/items/effectivity-module-5.png",
            icon_size = 32,

            subgroup = "module",
            category = "effectivity",
            tier = 1,
            order = "c[effectivity]-y[effectivity-module-5]",
            stack_size = 50,
            effect = { consumption = -0.9 }
        },
        {
            type = "module",
            name = "effectivity-module-6",
            icon = "__Darkstar2.0__/graphics/items/effectivity-module-6.png",
            icon_size = 32,

            subgroup = "module",
            category = "effectivity",
            tier = 1,
            order = "c[effectivity]-z[effectivity-module-6]",
            stack_size = 50,
            effect = { consumption = -1 }
        },

        {
            type = "module",
            name = "productivity-module-4",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-4.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-d[productivity-module-4]",
            stack_size = 50,
            effect = { productivity = 0.2, consumption = 4.9, pollution = 0.2, speed = -0.16 },
        },
        {
            type = "module",
            name = "productivity-module-5",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-5.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-e[productivity-module-5]",
            stack_size = 50,
            effect = { productivity = 0.3, consumption = 5.2, pollution = 0.4, speed = -0.17 },
        },
        {
            type = "module",
            name = "productivity-module-6",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-6.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-f[productivity-module-6]",
            stack_size = 50,
            effect = { productivity = 0.4, consumption = 6.5, pollution = 0.6, speed = -0.18 },
        },
        {
            type = "module",
            name = "productivity-module-7",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-7.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-g[productivity-module-7]",
            stack_size = 50,
            effect = { productivity = 0.5, consumption = 7.8, pollution = 0.8, speed = -0.19 },
        },
        {
            type = "module",
            name = "productivity-module-8",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-8.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-h[productivity-module-8]",
            stack_size = 50,
            effect = { productivity = 0.6, consumption = 8.1, pollution = 1, speed = -0.20 },
        },
        {
            type = "module",
            name = "productivity-module-9",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-9.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-i[productivity-module-9]",
            stack_size = 50,
            effect = { productivity = 0.7, consumption = 9.4, pollution = 1.2, speed = -0.21 },
        },
        {
            type = "module",
            name = "productivity-module-10",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-10.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-j[productivity-module-10]",
            stack_size = 50,
            effect = { productivity = 0.8, consumption = 10.7, pollution = 1.4, speed = -0.22 },
        },
        {
            type = "module",
            name = "productivity-module-11",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-11.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-k[productivity-module-11]",
            stack_size = 50,
            effect = { productivity = 0.9, consumption = 11.0, pollution = 1.6, speed = -0.23 },
        },
        {
            type = "module",
            name = "productivity-module-12",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-12.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-l[productivity-module-12]",
            stack_size = 50,
            effect = { productivity = 1.0, consumption = 12.3, pollution = 1.8, speed = -0.24 },
        },
        {
            type = "module",
            name = "productivity-module-13",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-13.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-m[productivity-module-13]",
            stack_size = 50,
            effect = { productivity = 1.1, consumption = 13.6, pollution = 2, speed = -0.25 },
        },
        {
            type = "module",
            name = "productivity-module-14",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-14.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-n[productivity-module-14]",
            stack_size = 50,
            effect = { productivity = 1.2, consumption = 14.9, pollution = 2.2, speed = -0.26 },
        },
        {
            type = "module",
            name = "productivity-module-15",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-15.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-o[productivity-module-15]",
            stack_size = 50,
            effect = { productivity = 1.3, consumption = 15.2, pollution = 2.4, speed = -0.27 },
        },
        {
            type = "module",
            name = "productivity-module-16",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-16.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-16]",
            stack_size = 50,
            effect = { productivity = 1.4, consumption = 16.5, pollution = 2.6, speed = -0.28 },
        },
        {
            type = "module",
            name = "productivity-module-17",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-17.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-17]",
            stack_size = 50,
            effect = { productivity = 1.6, consumption = 17.8, pollution = 2.8, speed = -0.30 },
        },
        {
            type = "module",
            name = "productivity-module-18",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-18.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-18]",
            stack_size = 50,
            effect = { productivity = 1.8, consumption = 18.1, pollution = 3, speed = -0.32 },
        },
        {
            type = "module",
            name = "productivity-module-19",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-19.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-19]",
            stack_size = 50,
            effect = { productivity = 2.0, consumption = 19.4, pollution = 3.2, speed = -0.34 },
        },
        {
            type = "module",
            name = "productivity-module-20",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-20.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-20]",
            stack_size = 50,
            effect = { productivity = 2.2, consumption = 20.7, pollution = 3.4, speed = -0.36 },
        },
        {
            type = "module",
            name = "productivity-module-21",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-21.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-21]",
            stack_size = 50,
            effect = { productivity = 2.4, consumption = 21.0, pollution = 3.4, speed = -0.38 },
        },
        {
            type = "module",
            name = "productivity-module-22",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-22.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-22]",
            stack_size = 50,
            effect = { productivity = 2.6, consumption = 22.3, pollution = 3.6, speed = -0.40 },
        },
        {
            type = "module",
            name = "productivity-module-23",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-23.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-23]",
            stack_size = 50,
            effect = { productivity = 2.8, consumption = 23.6, pollution = 3.8, speed = -0.42 },
        },
        {
            type = "module",
            name = "productivity-module-24",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-24.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-24]",
            stack_size = 50,
            effect = { productivity = 3.0, consumption = 24.9, pollution = 4, speed = -0.44 },
        },
        {
            type = "module",
            name = "productivity-module-25",
            icon = "__Darkstar2.0__/graphics/items/productivity-module-25.png",
            icon_size = 32,

            subgroup = "module",
            category = "productivity",
            tier = 1,
            order = "d[productivity]-p[productivity-module-25]",
            stack_size = 50,
            effect = { productivity = 3.2, consumption = 25.2, pollution = 4.2, speed = -0.46 },
        },
    }
)
